# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14d53dad3d0923b4c2779dd4a72b404dd8f2f96ef292f8ec0913a6cabcd649c7d14b1739f75e4f41eb5a6c0f26a53c3e5684b33cf9a281307ca467adbebd08c9

test:
  secret_key_base: 067e0e809e5837b8268d4d9fe52d047ed9afa552fc2ff66258ccb60876859c0cff49e8aa107c63b72a03fb7446e18023c4e2638e525a89a9fe68e903cd375377

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
